import "./App.css"


const Articles = () => {

 return (

   let article = ["If politics is a game best played in temperate weather, Kamala Harris’s arrival in Ripon, Wisconsin, on October 3 caught the luck of an unseasonably warm sun. It’s 71 degrees—by Wisconsin standards, summer—when Air Force Two touches down and Harris rides to Ripon College for a rally. As she nears, the twin downtown storefronts of the florist and the laptop-repair shop are playing Frank Sinatra ballads for passersby. Ripon, a flat, quiet city of fewer than 8,000 people, is a peculiar destination for the Democratic nominee for president: The Republican Party was founded here, in 1854. But for Harris, whose campaign seeks a stabilizing path against her opponent’s angry chaos, it’s a place, as fair as any, for the making of unlikely friends.

In an hour, Liz Cheney, the former Wyoming congressperson, former chair of the Republican Conference, and daughter of a vice president—a woman who has never voted for a Democrat for president—will endorse Harris onstage. Before heading out to join her, the vice president will meet me in the basement of the student union. Two chairs have been set up, angled toward each other, with flags between them. I’m shown to one, then the other. I am fussed over by aides, who readjust the draping of the flags. The process authority of American power, the way it calmly drives on like a swimmer down a clear lane, has rarely been so palpable to me; in the space of a few minutes I am greeted by more friendly and laconic people—coming in to check something, nodding, and vanishing again—than I can count. Photographers file in and take their positions, training their lenses on the chairs. I feel I’m entering bilateral talks on behalf of a small, wayward nation.

Image may contain Kamala Harris Elizabeth Cheney Ash Stymest Musashimaru Kōyō Clothing Footwear Shoe and Chair
MOMENT TO MOMENT
Harris with Liz Cheney at Ripon College in Wisconsin on October 3, 2024. Cheney, who has endorsed Harris, has never voted Democrat for president in her life.
Then the vice president enters amid a rain-like patter of footfalls, and the energy in the room changes. “Hi! How are you? Good to see you again!” Harris says, grabbing my hand and folding down into the opposite seat.

Related Video

Madison Bailey Only Uses Highlighter in One Place


Vogue Daily newsletter
Get essential fashion, style, and tips, in your inbox.

Sign up
By signing up, you agree to our user agreement (including class action waiver and arbitration provisions), and acknowledge our privacy policy.
She is dressed in an easygoing black suit with a plain white blouse, a few pearls on a double necklace, and black patent leather heels. Since becoming vice president, in 2021, Harris has sought reductions in gun violence, middle-class jobs in clean energy, drinking water for poor communities, and a strategy for Americans’ reproductive freedom. Before our meeting, I talked with more than 20 of her former colleagues and collaborators, who described Harris in these projects as a roll-up-the-sleeves leader. I ask what her first call would be on reaching the Oval Office.

“One of my first calls—outside of family—will be to the team that is working with me on our plan to lower costs for the American people,” she says. “It’s not just about publishing something in a respected journal. It’s not about a speech. It’s literally about, How does this hit the streets? How do people actually feel the work in a way that benefits them?” She says she plans to meet with “those who can help us put back in place the freedoms that have been taken away with the Dobbs decision”—the ruling that overturned Roe v. Wade—to get Congress to pass a law. “That’s going to take some work,” she says.

Work, one senses, is a happy word for Harris: What at first seem lucky breaks in her life tend on examination to reveal themselves as outcomes of strategic effort. The hurricanes that barreled into Florida in recent days and brought heavy destruction as far as inland North Carolina have required rescue and recovery from officials and ordinary Americans, and Harris has moved quickly on the ground to show them her support. But work can’t resolve every crisis. In recent weeks, the violence in the Middle East has grown, first with Israeli movement into Lebanon and more recently with a missile attack on Israel by Iran. I ask what “new element” voters can expect from a Harris administration in balancing the United States’ commitments in the region with attempts—so far unsuccessful—to de-escalate the conflict.

“A lot of the work that needs to be done,” Harris says, “is a function of the circumstances at the moment. I can’t anticipate what the circumstances will be four months from now.” She says she sees the role of the United States to create “incentives” for de-escalation and a “pathway” for stability, “including specifically as it relates to what’s happening in Gaza, as opposed to Lebanon.” Throughout her public campaign, Harris has nodded to two hard-to-square points of view on Gaza, affirming “Israel’s right to defend itself” against Hamas and Palestinians’ “right to dignity, security, freedom, and self-determination.” “A Harris administration—to speak of myself in the third person, which makes me quite uncomfortable—would be about articulating those points and hopefully bringing some language that is reflective of the complexity and the nuance of what’s happening in the region,” she says. Complexity and nuance, meaning what? I ask. Harris starts a couple of sentences, abandons them, and starts again.

The World of <i>Vogue</i> at Your Fingertips <br> Be at the forefront of fashion with the all-new, free Vogue app.<br> [CTA] GET THE APP
“There’s been a language and a conversation around what’s been happening, particularly around Israel and Gaza, that suggests that this is binary. It’s not,” she tells me. “You’re not either for this one or for that one.” A better conversation, she thinks, is about the region and its interlocking crises. “On October 7, 1,200 people were massacred, including hundreds of young people at a concert. Women were horribly raped,” she says, and pauses for emphasis. “And far too many Palestinians have been killed.” The United States must keep laying groundwork for a two-state solution, she insists, “not giving up a sense of hope that that is possible—even if it does not appear to be imminent.” In both foreign and domestic policy, Harris’s case for the presidency comes down in large part to her experience of the vice presidency—a role that she describes as being both active and receptive, learning not just how to solve problems but to consider what problems voters think they have, and how they overlay. “People, at this point, have memes about my love of Venn diagrams,” she says, and then turns serious. “You’re never going to have a complete agreement on all the issues. But you can find common ground—and expand that.”

Image may contain Kamala Harris Bernie Bickerstaff Adult Person Accessories Formal Wear Tie Clothing and Footwear
IN THE WINGS
Harris with Cheney before the event at Ripon College in Wisconsin.
It happens only rarely that individuals are summoned overnight for acts of national rescue, but in late July Kamala Harris received one of those calls. The presidential race had taken shape as one of the most consequential in history. Voters who remembered the troubles of the first Trump presidency—the rising unemployment, the decreasing health insurance coverage, the erosion of diplomatic alliances, the children separated from their families at the border, and the violent attack on the Capitol—saw an incipient emergency. “A second Trump term could mean the end of American democracy as we know it,” Trump’s own director of strategic communications during his final year in office told the press. (His supporters, ever faithful, saw only the possible return of their leader and of what they say were better times.)

On June 27, President Biden debated Trump in a performance many viewers found depleted. Within a day, donors, journalists, and elected leaders were calling for Biden to leave the race. The president, for weeks, said he would hold his course. Then something changed. On the morning of Sunday, July 21, Harris rose early and joined the two young daughters of her niece, who was visiting. “We were the first ones to wake up in the house,” she explains. “They were talking with me while I was working out, and I had a cooking show on. That’s my way of getting away from politics—watching the food channel.” The girls and Harris, still in her workout clothes, made pancakes and bacon, and settled down on the floor, around the coffee table, for a puzzle. The phone rang.

“It’s Joe Biden,” Harris recalls. He told her he was leaving the race, and hoping to endorse her in his place. As she dryly puts it, “This was a dramatic turn to the day.”

Image may contain Adult Person Clothing Footwear High Heel Shoe Flag People Plant Coat Crowd and Walking
THE MIDDLE
Harris, here in Wisconsin, is often described by those who’ve worked with her as a results-oriented, roll-up-the-sleeves leader.
Harris called her husband, Doug Emhoff, who was stranded in Los Angeles—it was the week when a computer glitch grounded thousands of flights—but she couldn’t get through. “​​I’m like, Where is he? Somebody find him! Why isn’t he answering?” she recalls. “And I could not reach him for the world”—she tries to contain herself, but cracks up—“because he was in a SoulCycle class.”

Indeed, the second gentleman was at that moment perched atop a stationary bicycle, working out with a buddy, as one often is on Sunday mornings in LA. He had left his phone in the car with his Secret Service detail. When the hour of SoulCycle was through, he, his friend, and his friend’s partner caught up over coffee. Suddenly his friend’s partner lifted his phone: “‘I think you need to see this,’” Emhoff recalls. The second gentleman sprinted back to the car. “There was, like, steam coming out of my phone,” he says. “There were so many messages, and all the same message, which was: Call Kamala.” So he did. “She literally just said, ‘Where the eff were you?’”

Her day had become an industrious blur. By the time Emhoff talked to his children, Cole and Ella—“just let them know what was going on and to strap in”—and commandeered the kitchen table of their LA house with a big pot of coffee, his wife had gathered her team in the dining room at One Observatory Circle. “The big joke around the table was, Who here had actually showered?” Harris recalls. She contacted elected and community leaders to set her candidacy in motion; by the end of the day, she’d made about a hundred calls. “We brought in pizza,” she says. “Everyone was just around the table doing some aspect of everything that needed to be done. Because, of course, the world was aware of what happened that day.”

Across the globe, alliances, markets, and lives rely on the steady pulse of the American presidency. When Biden’s announcement caused that pulse to drop a beat, the world looked to Harris with hopes and doubts. She was a leader of widespread support but no especial following. Her first run for the presidency, five years earlier, had foundered out of the gate. Now, at her dining room table with pizza boxes, a trusted unbathed staff, and a phone, she was being called on to do something unprecedented in American history: to mount, and win, a presidential race in three months, as a woman of color, with a felonious former leader as the opposition and the future of democracy said to be at stake.

Image may contain Lucia Annunziata Kamala Harris Susann Goksør Bjerkrheim William E. Moerner and Miroslav Singer
FACES IN THE CROWD
“You’re never going to have a complete agreement on all the issues. But you can find common ground—and expand that,” says Harris, here seen campaigning in Wisconsin.
That was two months ago, but it seems like an eon. The groundswell of energy that emerged over the next weeks has defined this moment. Grassroots fundraising groups proliferated on social media: South Asians for Harris, White Dudes for Harris, Cat Ladies for Kamala, and so on. By August, the campaign had enrolled a huge number of volunteers, the vice president was edging past Trump in polls, and endorsements were ringing in: Harris may be the only candidate ever to make bedfellows of Dick Cheney, Bernie Sanders, Vinod Khosla, Taylor Swift, and Chris Rock. Across the country, voters disturbed to see women robbed of agency and health care rallied to a candidate unshy of leading with reproductive freedom. “She was like, Well, why don’t we bring in labor? Where are the women’s organizations focused on paid leave? What about the orgs that are focused on, like, the Divine Nine sororities? What about women in faith? What about men?” recalls Mini Timmaraju, the president of the advocacy organization Reproductive Freedom for All, with which the vice president started meeting even before the Dobbs decision. “Many of us were already doing that work together, but we weren’t being asked to by folks at the White House.”

Most people first encountered Harris as a junior senator from California, when she became known in hearings for cross-examinations of the sort that might leave char marks on a steak. Usually, she had just five minutes of floor time. “She was normally the last senator to ask questions, and oftentimes senior senators had taken up the more obvious ones,” Rohini Kosoglu, Harris’s chief of staff in the Senate, recalls. “So she would get back to, Why are we here? If people watch for those five minutes, how can we help connect the dots to help them understand what we’re doing?” Harris’s concise, unsparing interrogations—of former attorney general Bill Barr, of Meta CEO Mark Zuckerberg, and in longer form of Supreme Court nominee Brett Kavanaugh—became eminently shareable emblems of accountability-seeking, and a template for the viral exposure she got again this summer. When Charli XCX posted “kamala IS brat”—a reference to her own chartreuse-colored album—a parade of Gen Z memes followed her cue. The Harris campaign, in a nod to this recognition, turned the backdrop of its social media pages green.

On August 6, one of Harris’s first big rallies brought 12,000 people to a packed hall in Philadelphia, where she was to introduce her pick for running mate, the former teacher and football coach and current Minnesota governor, Tim Walz. The mood inside was vaporous. “To see the young people, older people, Republicans, men, women rally around her was electrifying and made me think that, in America, anything is possible,” Yvette Young, a Philadelphian who had come to hear her, told me. “It brought back a feeling that’s been gone for me since Donald Trump came down the escalator.”

“I like the way she’s handled criminals and gun law,” Tyreisa Williams, a young, elegantly dressed woman watching attentively, said. A woman named Julie Sandler sporting chartreuse-colored hair and a chartreuse romper told me, “I’m a fashion girlie! And a socialist! I thought the path to victory was getting narrower and narrower, but with Kamala it’s expanding.” Shared ideology bound the audience less than shared will. The right-wing former congressman Joe Walsh was roaming. “There’s plenty of policy I disagree with this ticket on, but there’s some I agree with, and, most importantly, she’s got to beat Trump,” he told me. “He’s an existential threat to our democracy. He’s unfit.” Another Republican, the former congressman Jim Greenwood, said, “When the debate happened, my response was, I don’t care if Biden can do one-hand push-ups and recite the Bible backward—you’re never going to unsee that. As soon as the switch was made, there was an electric charge.”

Onstage, Pennsylvania leaders worked the crowd to higher voltage. The hall was stacked 12,000 people high. Harris and Walz, when they appeared, set off a roar so strong it drowned out the vice president’s first words.

She pushed through with a grin. “We’re doing this,” she said. “Last night, the delegates to the Democratic National Convention finished voting. And I stand before you today to proudly announce: I am now officially the Democratic nominee for president of the United States.”

Image may contain Roy Hargrove Sgt. Slaughter Adult Person Clothing Hat Footwear Shoe High Heel Coat and Officer
GROUND GAME
Harris at Detroit Metropolitan Airport on October 4, 2024.
Chasing the future often casts Americans back on their pasts. In November of 2021, Harris and the second gentleman visited the Institut Pasteur in Paris to get new information about cutting-edge COVID research. “To attack this problem, we have a simple tool: the nasal swab,” James Di Santo, an immunologist, told her. He produced a swab and held it reverently aloft.

“I’m intimately familiar with the nasal swab,” the vice president said.

Her wry conviviality covered other emotions. Privately, Harris described the visit to the Institut as one of the most moving of her time as vice president. Her mother, Shyamala, a cancer researcher who had died 12 years earlier, had worked in those laboratories, doing mRNA research related to the kind that later helped produce a COVID vaccine. Harris met with Étienne-Émile Baulieu, a 90-something endocrinologist with whom her mother had published. “It was an emotionally meaningful meeting for her,” Emhoff remembers. “It was a way to honor her mother in a place where she achieved so much.” Both of Harris’s parents were scholars (her father, Donald, is a retired economist), but it’s her mother, retaining custody of Harris and her younger sister after a divorce, whom friends closely associate with Harris’s personality and laugh.

“Shyamala was an extraordinarily brilliant woman—she had a great sense of humor, cooked, played cards, was well-read, and was fun,” Matthew Rothschild, a friend, former colleague, and longtime LGBTQ advocate who became close to Harris’s mother, says. “What is that characteristic some people have that you’re just proud to be their friend?” In Friends from the Beginning, Stacey Johnson-Batiste’s 2021 memoir of her friendship with Harris, she writes of Shyamala and her own mother ferrying their children around Berkeley. Harris, even at five, fascinated her. “I had never seen anybody else my age wearing such an abundance of beautiful bracelets,” Johnson-Batiste writes. “They were Indian bracelets: fuchsia, yellow, teal, and other vibrant colors, framed by tiny rhinestones that glistened and jangled as we walked.”

As children, Harris and her sister would travel to Chennai to visit their maternal grandparents, who had an arranged marriage (though her grandmother was said to have spent the 1940s driving through villages shouting at women through a bullhorn to tell them to get birth control). According to Rothschild, who sometimes joined Harris at her mother’s place, Shyamala proudly kept a Ganesh in her home and a collection of saris in her closet, yet she was also invested in the Black lineage of civil rights work in the East Bay. (“She wanted her daughters to grow up as Black women,” Rothschild says.) Johnson-Batiste remembers her driving the kids to Rainbow Sign, a Black cultural-arts center, in Berkeley, visited by writers such as Maya Angelou and James Baldwin.

At 12, Harris moved away, when her mother followed a job to Montreal, where she went to public high school. (“There were different types of kids, some very rich, some very poor, and she was able to bridge the gap so it didn’t seem there was a gap,” Wanda Kagan, one of her friends there, says. When, in their last year, Kagan revealed that she was being physically and sexually abused at home, Harris and her mother took her in to live with them.) After Howard University, where Harris earned a degree in political science and economics, Harris returned to San Francisco for law school and, rather than signing on to a big firm, went into public prosecution. By 2000 she was working for San Francisco’s city attorney, Louise Renne, with an assignment to lead the child and family division, not traditionally seen as a plum job. “You’re dealing with families in crisis and kids at risk—it’s emotionally difficult, and, personally, I couldn’t do it,” Dennis Herrera, the city attorney who succeeded Renne, says. Harris made the division her own, prosecuting elder financial abuse and the sex trafficking of teens. “She was held in very high esteem in that office,” Scott Wiener, now a California state senator but then a junior lawyer with the city attorney, says. When the judge at his first jury trial chewed him out, Wiener stumbled into Harris’s office for advice. “Kamala said, ‘She probably knows this is your first trial, so she’s testing you—don’t let her push you around.’”

Wiener volunteered for Harris during her run for San Francisco district attorney: a race that she entered polling in the mid single digits and was expected to lose. Her opponents were a powerful incumbent on the left and a well-known law-and-order candidate in the center. In the one-party politics of San Francisco, oriented by divisions within the blue—between, say, a Biden and a Bernie—she seemed to have no path. “She came up the middle, which is a hard thing to do,” Wiener says. “But she was able to figure out who on the left was not fully committed to the incumbent, and who on the more moderate side may not have wanted a hard-line, old-school mass-incarceration approach.” She met with people one by one. As that election drew near, the campaign formed advisory groups: Filipinas for Kamala, LGBT for Kamala. “You can’t win in San Francisco if you’re not a coalition builder,” Rothschild, who also worked on that campaign, explains. “I can remember doing postcards to people who requested their ballots in Vietnamese, in Russian, in Tagalog. It was all very finely targeted.”

Harris ended up winning that impossible-seeming race by more than 10 points: the first woman and the first person of color in the role. Nancy Pelosi, the longtime San Francisco congresswoman, who had supported the incumbent, was startled and impressed by Harris’s showing—and by her strategy. “It was quite remarkable,” Pelosi tells me. “She had a fresh approach, a new approach, and she won.”

Colleagues recall Harris’s DA office as a high point for function and a low one for polarized debates about “hardness” versus “softness” on crime. Her collaborators today still describe her as pragmatic and non-ideological—a thinker who reasons not in abstract ideals but in results. (“Her first move isn’t to the podium to wag a finger,” a former adviser tells me; instead, she tends to feel out privately how people might be brought aboard.) She is said to have an eye for the long game. In 2004, while district attorney, Harris squired around an Illinois state senator who had come to San Francisco to fundraise for his first US Senate run: Barack Obama. Her judgment in most things, her colleagues say, has directed intent. Wiener recalls running into Harris on election night in 2007, when he was chair of the county Democratic Party.

“I stopped by the polls on the way to the gym, so I was in my gym clothes,” he remembers. “Kamala was there because she was on the ballot for reelection as district attorney, and, in classic Kamala fashion, she was perfectly put together and looked amazing.” (Rothschild: “I remember one time I saw her coming out of a dental surgery and she looked great.”) “I’m like, ‘Oh, hey, Kamala!’”

In Wiener’s telling, Harris looked him up and down, gym top to gym bottom. “She’s like, ‘You need to look the part,’ and turns around and walks away,” he recalls. “It left a psychological imprint on me. Now I’m a state senator, and sometimes when I’m making a choice about how to dress—do I go a little more formal or a little more casual?—I hear Kamala’s voice in my head saying, ‘You need to look the part,’ and it helps me decide. Literally to this day. And that was 17 years ago.”

No one could say that Harris didn’t look the part on the last night of the Democratic National Convention when, dressed in a navy Chloé suit designed by the German-American designer Chemena Kamali and a matching silk blouse with the lavallière bow that has become her signature, she strode onstage to accept her party’s presidential nomination. The look was military, judicial, stabilizing, powerful: an advance vision of the commander in chief. The set behind her had been lighted to an institutional wood-panel brown. “You can always trust me to put country above party and self—to hold sacred America’s fundamental principles, from the rule of law, to free and fair elections, to the peaceful transfer of power,” she said: words that seemed a caption to the image. Pundits admired the speech for walking the tightrope of a fraught moment—coming up the middle—with confidence and control.

Image may contain People Person Adult Chair Furniture Accessories Bag Handbag Clothing Glove Box and Footwear
FIRED UP
Harris at the Redford Fire Department in Michigan, a state that is widely seen as key to an Electoral College victory.
The care and restraint of the vice president’s address stood in contrast to the convention’s festival mood. It was the second couple’s anniversary. Speakers described the ticket as a breezy relief from bitter Trumpism. The previous evening, Oprah, wearing purple, cried, “Let us choose truth, let us choose honor, and let us choose”—she spread her arms and took a big breath—“jooo-oy!”

The night before that, the Obamas were onstage, talking of the excitement that they felt, alluding to the heady magic of their own ascent (“a familiar feeling that’s been buried too deep for far too long…the contagious power of hope,” as Michelle Obama put it). Yet one noticed the difference between their long-ago campaign and Harris’s. For the past 20 years, the United States has been a unicorn-chasing society, always on the prowl for golden outliers. Obama’s campaign, which rode the story of his own exceptionalism to victory, marked the high reach of that effort. But unicorn-chasing has taken its toll—in politics, perhaps, but even more in business and in life—and high-flown rhetoric and wide-cast hope now leave some Americans feeling emptied. For years they pinned their dreams to shooting stars, who glowed with authenticity before tracing their own special paths into the night.

Harris’s speech was different, and announced a new era. “The middle class is where I come from,” she declared, and ran through her résumé not as a meteoric leader but as a worker, a woman who commuted and did her best. “I stood proudly before a judge, and I said five words: Kamala Harris, for the people.” No mystique, sure, but also no mystery: no smoke, no mirrors, no soaring ideals, no Icarian ascents. She was the wonder with her feet on solid ground—as speakers at the convention kept underscoring, “one of us.”

“You’re never going to have a complete agreement on all the issues. But you can find common ground—and expand that.”

Also different: She wore no white. Unlike many women onstage and in the arena, unlike Hillary Clinton accepting the nomination eight years earlier, Harris had forgone women’s-suffrage tones in favor of her Oval Office blues. In her speech, she didn’t once underscore the prospect of becoming the first female president or the first president of nonwhite immigrant parentage, a departure from the primary campaign she ran for president five years ago.

In 2019, Harris had cast herself as a fast-rising star, a woman of immigrant background who would bring those identities to the White House. And yet offering herself as an emblem, as Obama had done, brought her up short. “At her launch speech in 2019, there was a tremendous groundswell of support,” one of her top staffers on the campaign recalls. “But she didn’t have a solidified base.” Polling that fall revealed that Harris was the top choice of only 4 percent of Black voters, and she struggled to fundraise. In Vox, the writer Shamira Ibrahim suggested that Harris’s error was in emphasizing what she represented—the historic elements of her ascent—more than who she was. “Banking on identity wasn’t enough,” Ibrahim wrote. “Because aside from being a Black woman and former prosecutor with ties to Obama, many still wondered: Who is Kamala Harris?” She dropped out before the first primary.

This year, her campaign and its close supporters have made a point of treading lightly on the “historic” elements of the run. Identitarian banners are carried mostly by third-party coalitions that micro-target donors and voters (“South Asian Women for Harris”), while the big campaign runs on the idea that voters care less about history being made than about whether they know the candidate they’re choosing. “The trap—and I can say this as a woman-of-color executive myself—is when you focus on identity they start to use their, frankly, tired old racist tropes, and you don’t want to walk right into that nonsense,” Mini Timmaraju, of Reproductive Freedom for All, says. “That doesn’t mean you’re not proud of who you are; it means you understand the dynamic that we’re in. Kamala Harris said nothing, and Donald Trump is already making fun of, Is she Indian? Is she Black? It’s a useless, unhelpful discussion for her to have when she is exceptionally overqualified for the president’s job.”

With four years of executive-branch experience behind her, the thinking goes, the vice president can now afford to run as herself. Old associates, like Wiener, note with relief that the Harris who comes across in viral remarks like “You think you just fell out of a coconut tree?”—her mother’s wisecrack about the importance of being attentive to history and inter-dependence—was the Harris they knew. Others describe the diplomacy with which she sewed up her party’s nomination as classically Harris-esque.

“We had wanted—we thought that there would be—an open convention,” Pelosi, who was among the influential Democrats to hold that the Biden campaign might not be a winning one, tells me. Harris recognized conflicting loyalties within the party and, rather than trying to conquer them, went around telling supporters of her putative challengers that she understood their other allegiances. “It was easy for people to come to her because they knew she didn’t have bad feelings toward them,” Pelosi explains. “And then she—boom!—one, two, three, wrapped it all up. It was a beautiful thing. Anyone else could have gotten in the race. But by then they knew that she was on a path”: an expedient route to a clear outcome.

“I wasn’t really talking about who would be next,” Pelosi insists of her interest in a revived ticket, then adds, “but I always thought if there were an open convention, she would win it.”

Acouple of weeks after the convention, at a rally outside Portsmouth, New Hampshire, a crowd presses at the edges of a makeshift stage set within a hot oval of bleachers and mowed grass. It’s a clear, bright afternoon just after Labor Day—what in a normal year would be the beginning of the final rush to the election but now marks the hard core of the campaign. A stand nearby dispenses themed refreshments: the “Kamala Femininomemon” (a lemonade) and the “Coach” (iced tea). By half past two, the bleachers are packed; a helicopter tracks the scene overhead as men and women with earpieces make quickening tours. Onstage, Maggie Hassan and Jeanne Shaheen, New Hampshire’s Democratic senators, warm up the crowd with praise for the vice president.

“U-S-A! U-S-A!” the crowd chants. “Ka-ma-la! Ka-ma-la!” The audience’s energy has begun to overflow its container, something hard to imagine two months earlier.

“Part of what I do is drive around and look at lawn signs,” Dan Rowntree, a gray-bearded volunteer for the campaign smoking behind some bleachers, tells me. Sign-counting is his effort to gauge Nashua-area residents’ enthusiasm and social confidence in their choices. “When I drove around two months ago, I counted 35 signs for Trump and one for Biden.” By late August, he saw two signs for Trump and 11 for Harris, plus some light-up coconut trees. New Hampshire is presumed to be an election bellwether—but the mood was far from settled. “I have daughters, and I have granddaughters,” Tracy Janelle, from nearby Newmarket, tells me. “But I’d like to hear more about policy.”

Behind closed doors, some say, Harris’s methods and her policy have long been intertwined. “She’s very outcome-focussed,” Bharat Ramamurti, the former deputy director of the National Economic Council, who unofficially advises Harris’s campaign, tells me. “Like, if we say we want to deliver affordable broadband to people, how do we get from the federal funding to the actual affordable broadband delivered to somebody’s home?” Working on medical-debt relief for low-income veterans, he says, Harris became intensely concerned with details as practical as the paperwork veterans had to fill out. Kosoglu recalls, “She’ll say something like, ‘If you’re a father who has to wake up, take your kid on the bus, drop them off at child care, and get back on to get to work—how is this going to work? And what she’s really saying is, ‘You guys are talking to me theoretically. Let’s play it out with a case study.’” Marty Walsh, the former secretary of labor, with whom Harris led the White House Task Force on Worker Organizing and Empowerment, says, “Where you really saw her shine was in the working groups, asking questions and digging into the details.”

“It was easy for people to come to her, because they knew she didn’t have bad feelings toward them,” Nancy Pelosi says of the days after President Biden dropped out. “And then she—boom!—one, two, three, wrapped it all up. It was a beautiful thing.”

At the start of the campaign, most of Harris’s policy was inherited from Biden. (His emphasis on infrastructure and clean energy remains.) More recent focus points, however, have been hers. Some reflect her early work in child-and-family law: In 2021 she cosponsored expansion of the Child Tax Credit, which offers Americans up to $2,000 per child. (On the trail, she says she wants to bring it to $6,000.) In the Senate, she began trying to replace all lead pipes in the country—a source of disasters, as in Flint, Michigan, that often affect low-income children—and continued the project as vice president. She was the force behind work culminating last year in the creation of the White House Office for Gun Violence Prevention, which generated more than 50 executive actions and the first major gun-safety bill in nearly three decades, addressing everything from trafficking to the training of 14,000 new mental health care professionals in schools. “She requested that we pull together ideas for every government agency in preparation for her first big Cabinet meeting—and that was literally Day One,” the program’s deputy director, Greg Jackson, says. “Our team had to come up with ideas for executive actions before we could get into our office.”

Harris explains that she sees improving the lot of parents and children not just as a social good but as economic planning. “So much of how I think about policy generally is, Let’s think about the future we can create and then plant the seeds right now,” she tells me in Wisconsin. “Part of the way we get ahead is when we have options—when we’re not relegated to one situation or status or confined to only one choice.” Harris has stepped back from the idea of college as the sole endpoint of a great education, arguing that skills-based training, the kind that formerly led to technical trades or factory-floor management, is needed in domains like clean energy. “I love apprenticeship programs,” she says. “Let’s think about the pathway and the opportunity for them to get into industries of the future, be that biomanufacturing or how we’re thinking about the future of technology, from AI to quantum computing.” (Harris is so bullish on quantum computing, one former staffer tells me, that her longtime advisers collectively smile every time she drops the phrase in meetings.)

For middle-class Americans chasing a better life, she holds, the big obstacle is access to capital—to start a business, to buy a home. One of Harris’s signature legislative moves for years has been investing in community development financial institutions, or CDFIs, which help struggling communities with that access. On beginning as vice president, one of her former advisers tells me, her first meeting outside government was with small-business owners, and the following day, she started calling the CEOs of big banks to lean on them to move more money out the door to small enterprise.

When I ask about her focus on CDFIs and small business—essentially, a market-based approach to aid—Harris describes those measures as having a double benefit: “What it does to strengthen the economy of the community, but also the cultural fabric. It’s not just business. These are usually meeting places, the place that you regularly go for brunch with your friends or the place where you always get your morning cup of coffee. Or the local dry cleaner.” The difference between a community that generates its own businesses to serve its own needs and one served by corporate chains or remote programs is profound, she thinks. “If you walk into that restaurant where you go often or you grew up going, they look at you and say, ‘You doing okay? You having a bad day?’” she says. “And looking at it entirely from an economic, policy perspective: They hire locally, they train, they pay the taxes that are going to help repave the sidewalk outside and make sure the street lights are lit.”

Today, the backdrop of the New Hampshire stage reads “Opportunity Economy: Supporting Small Businesses” in giant letters. In a style both casual and precise—Harris wears one of her many taupe blazers, with trim charcoal jeans and pointed stilettos—she lays out details of her program onstage. The tax deduction for new businesses would rise tenfold, to $50,000, and loans of low and no interest would flow to small businesses trying to expand. Access to “venture capital” and “innovation hubs” would be set up in towns and rural areas, and capital-gains tax for high earners would come down from Biden’s plan, to 28 percent (“a rate that rewards investment in America’s innovators”). Also—the Harris touch—simplified tax paperwork: “Kind of like the 1040EZ,” she says. There is a cheer.

After the rally, Harris pays a visit to Port City Pretzels, a nearby factory owned by a mother-daughter team. Most of its employees are disabled.

“You didn’t start with this, obviously,” the vice president says when she arrives, glancing with some wonderment around the factory, which is filled with equipment and enormous crates of, one imagines, pretzels.

“We started with 500 square feet,” Suzanne Foley, the co-owner, says. “It’s hard work.”

“It’s good work,” the vice president says. The press pool leaves.

“I would love to give you a bag of pretzels,” Foley says.

“Give me a bag of pretzels—to give Doug,” Harris says. “He secretly eats pretzels at night. I’m like, ‘Honey, you got to slow down on the pretzels….’”

“It’s a resealable bag,” Eileen Marousek, Foley’s daughter and co-owner, who is pregnant, offers.

The vice president examines the bag with studious attention. “Oh, that’s—” She seems for a moment at a loss, or maybe overcome. The pretzels are of Tasty Ranch Dill flavor. “Yum!” she exclaims. “Yum!”

“You have a lot of people behind you,” Foley says, still eyeing the pretzels.

“Sixty-two days,” Marousek notes. “You can do it.”

Fifteen days later, in a place called Farmington Hills, Michigan, Harris recalls the pretzel factory. “It’s an example of the blessing I have in being able to travel the country and meet the heroes walking among us,” she tells me, “people who are not looking for that kind of attention. I told her, ‘Make sure you tell your story,’ because if more people hear it, it might inspire them to say, ‘I could do that.’”

We are standing in a side room of the Studio Center, where Harris and Oprah are taking photographs with dignitaries and supporters before broadcasting a show together—two women whose singular jobs might reflect the highest reach of I-could-do-that inspiration in the land. Harris wears an eggplant-colored suit and a black pinstripe blouse. Oprah wears burnt orange on burnt orange. On landing at the Detroit airport, the vice president descended from Air Force Two to greet the Boys & Girls Clubs of Southeastern Michigan, lined up in a double row. A boy welcomed her Peter Pan–style, hands at his hips. She mirrored him. She admired a girl’s glasses and marveled at the accomplishments of a young man. Her bodywoman approached—“Madam Vice President, it’s time to go”—but Harris ignored the summons until she’d met everyone and gathered them for a photograph. “Okay,” she said. “Let’s come together.”

Small businesses help local economies but also “the cultural fabric,” Harris says. “These are usually meeting places, the place that you regularly go for brunch or the place where you always get your morning cup of coffee.”

Now, alongside Oprah, perched between two draped flags, she poses with her adult supporters.

“How are you?” Oprah says.

“I met you in Chicago!” someone exclaims.

A local political adviser rounds a corner for a photograph and freezes, looking back and forth between Harris and Oprah.

“I was only prepared for one!” she exclaims.

The broadcast will be streamed live on the web and on channels across the country, but the taping location, in the Detroit suburbs, carries weight: In 2016, Trump won Michigan by a hairbreadth of 11,000 votes, and Biden and Harris won it by just 154,000 in 2020. The vice president’s surest path to Electoral College victory requires her winning Michigan, Wisconsin, and Pennsylvania as a trio.

The debate with Trump was only days behind her. She’d offered the former president bait, and he had taken it. When she suggested that people were bored at his rallies, he used time to insist otherwise. He concluded, of immigrants, apropos of nothing, “In Springfield, they’re eating the dogs! They’re eating the cats!” To some, the performance had seemed a signature Harris acceleration: entering a competition neck-and-neck and, through strategic moves, zooming ahead. (Her success with an abrasive Trump stood in contrast to the vice presidential debate, between Walz and JD Vance, which commentators took to be better mannered—and at best a draw for Walz.)

The acceleration reminded some of her run for California attorney general, in 2010: an election she was presumed to have lost. “On election night, many people said to me, ‘Oh, I’m so sorry about your friend,’” Matthew Rothschild recalls. Some California papers called the election for the opposition. About a million Los Angeles County ballots were still out, but Harris’s opponent, at that point up some eight points, was the thrice-elected district attorney of Los Angeles, and Harris could hardly be expected to beat him on his own turf—right? Wait, her campaign said.

Harris had carried her San Francisco coalition-building strategy statewide. On January 3, 2010, “Latinos for Kamala” had been founded out of Los Angeles. In the primary, in some largely South Asian counties, she ended up with a double-digit lead. The Republican strategist Karl Rove infused a million dollars into her opponent’s campaign—a sign, many thought, that he saw the Democrats’ future in her. (It is an irony, perhaps even a sweet one, that in this year’s presidential election, Rove praised Harris in her race against Trump.) And, as vote counting continued overnight, there was startling news: Los Angeles had gone to Harris, who now led overall by two-tenths of a percentage point. Her statewide margin grew as tallies continued. On the eve of Thanksgiving, her opponent conceded.

Winning that election changed her future. “People knew that the next governor or senator would be Kamala or Gavin Newsom,” a former staffer tells me, adding that the two had “a healthy competition” dating back to early San Francisco races, when they crossed paths fundraising. And it was the start of her national political legacy. As attorney general, Harris pursued projects in consumer protection, environmental accountability, fair policing, and child safety.

Image may contain Townley Haas Kamala Harris Ximena Rubio Tamim bin Hamad Al Thani Robin Peterson People and Person
FROM ME TO YOU
Harris’s campaign has treaded lightly on the “historic” elements of her run.
At the same time, her life was changing from within. In 2013 she was set up on a blind date with Emhoff, a divorced lawyer, who—as he put it in his winsome, unassuming speech at the convention—rang her up at 8:30 a.m. and left a rambling message: “Hey, it’s Doug….” A year later, they married. “Everyone talks about how proud Shyamala would be of Kamala’s leadership and nomination for president of the United States,” Rothschild says. “But I’ll tell you what she’d be most proud of: That she met Doug and his family and his kids.” For years, her mother had confided to Rothschild worries about her brilliant, hardworking daughter not having the grounding of a family. “Because you’re president for four or eight years, and then what?” he says. “You’re back to your family—for life.”

Emhoff tells me, “Kamala was very mindful of not meeting the kids until she and I were established as a couple, and it looked like it was going to really go the distance, as she herself was a child of divorce." When the time was right, Harris came to the house bearing cookies, and they drove together to one of the kids’ favorite restaurants, a counter-service fish joint in Malibu called Reel Inn. “I went to the bathroom and then, you know, kind of waited an extra five or seven minutes under the guise of having a ‘business call,’ so I could let them spend some time together,” Emhoff says. “By the time I got back, they were laughing.” On the way home, the kids asked to stop off at Art Night at their school—an event they hadn’t previously told him about—and started introducing Harris to their friends and their friends’ parents: All at once they were four, a unit. “Pretty soon after that Kamala became Mamala,” Emhoff says.

Today, Harris describes Sunday family dinners as her precious respite, a chance to step back from her weighty, never-ending duties. If it’s the season, Emhoff will be watching football. “I’ve got some music going,” she says: Beyoncé, Bob Marley. Maybe she’s making her “world-famous roast chicken,” as the family wryly calls it. Or her “world-famous Bolognese,” which cooks for five hours. “It’s just the family there,” she says. “That’s my very happy place.”

Harris’s task during her appearance with Oprah is to connect with the American people on air: a gigantic-family-weaving feat of which the Queen of All Media is the world’s leading virtuoso. At five minutes to broadcast—to the second—Oprah bursts from her greenroom, briskly crosses the dark of the wing, and walks onstage to greet and warm up her audience, seated in the round. As the show opens with a mini documentary, she positions herself, clocks her cameras, sets her shoulders, and, at the moment when the red light flicks on, is there—Oprah!—relaxed and authoritative, the nerve center of the room.

“I am here because I care deeply about the future of our country, and I know that all of you do, too,” she declares, drawing her fingertips together. “We just saw on the tape this grassroots, people-powered movement behind Kamala Harris has unleashed a unifying force unlike anything we have seen in politics in a very long time.” The audience of 400, with a thousand more logged in as visible windows on a large screen, cheers.

Backstage, there’s silence; Oprah’s makeup artist passes with her kit. “Oprah looks good,” someone whispers. The artist nods with quiet pride, and moves on.

Then all at once the backstage clears, and a solitary figure slips into a folding metal chair before a monitor. It is the vice president. In the dark, she seems to allow herself the greatest luxury for someone who, for more than a month, has been everything to everybody on daises and cameras all the time: to be invisible. Harris brings her hands palm to palm, tucks them between her knees, and lets her shoulders fall forward and her neck tilt up toward the monitor, rolling a lozenge on her tongue. For a few moments, she seems truly “one of us”: an American, tired after a day of meetings and travel and speeches, giving way to gravity and TV. When Khalil Thompson, the founder of Win With Black Men, notes that Trump took credit for checks issued by congressional approval, she grins—a TV-watcher’s private grin, not a camera smile.

Soon enough, the world rushes in. A couple of Harris’s top advisers take the folding seats beside her and begin whispering in her ear. The private moment breaks, and she sits back in the chair, crosses her ankles, crosses her wrists, and focuses her eyes on the screen: She’s now the leader for whom hundreds of thousands of volunteers all across America are working around the clock, knocking on doors, making phone calls, hosting Zooms. When Gretchen Whitmer, the governor, speaks, Harris nods gratefully.

The Secret Service clears a path, and leads Harris to a dark wing. A stagehand gestures for her to hold; she crosses her arms and narrows her eyes toward the floor, as if gathering her thoughts. Then, in the final moments, she looks up, up—to the scaffolding bearing stage lights, to the theater ceiling, maybe to something else.

“In no other country on this earth could her story unfold the way it has,” Oprah is saying. “From a child of immigrants, to big sister, to McDonald’s worker—there is hope for y’all—district attorney, to wife and Mamala, to senator to vice president—please welcome….” The crowd springs to its feet, the stagehand gives a go-sign, and Harris rushes forward, into the light."];


let article2 = ["We all have that one obsession that informs our personal style, and for me, it has always been jeans. Growing up as a fashion lover in rural Canada, with no access to the hottest new brands or covetable designer items, I developed a fascination around working with what I could find locally—denim—and making it feel avant-garde. Super-skinny jeans, ripped jeans that were splattered with paint; I took delight in finding the most off-kilter pairs, often DIY’ing them to make them even more weird. Today, my closet is still overflowing with jeans—from baggy to skinny to flared. They're my kryptonite! And can you blame me? They’re a classic wardrobe staple for a reason: They go with virtually everything.

As a professional denimhead, I was naturally intrigued by all of the jeans bags on the fall 2024 runways. Clearly, I already love a denim pant, but why have I never considered denim accessories? At Loewe, the slouchy hobo bags came in a clean light-wash jean; At Diesel, the shoulder bags were more frayed and distressed, while Marine Serre showed a monogrammed style with leather straps. Paired against dressier pieces like sleek knits, leather trenches, and floral dresses, the jean bags gave each look a casual-cool nonchalance. I was instantly hooked."];
 )
  
}
export default Articles; 
